spring:
  jpa:
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org.springframework.jdbc.core.simple.SimpleJdbcInsert: DEBUG